# Generated by Django 6.0 on 2026-01-24 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
                ('rank', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='renda.deck')),
            ],
            options={
                'indexes': [models.Index(fields=['deck', 'rank'], name='renda_card_deck_id_5d456e_idx')],
                'constraints': [models.UniqueConstraint(fields=('deck', 'rank'), name='uq_card_deck_rank')],
            },
        ),
    ]
