# Generated by Django 6.0 on 2026-01-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renda', '0002_card'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='card',
            name='uq_card_deck_rank',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='renda_card_deck_id_5d456e_idx',
        ),
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('deck', 'position'), name='uq_deck_position'),
        ),
        migrations.RemoveField(
            model_name='card',
            name='rank',
        ),
    ]
