# Generated by Django 6.0 on 2026-02-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renda', '0003_remove_card_uq_card_deck_rank_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='uniq_tag_name_per_user',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='card',
            name='uq_deck_position',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='position',
        ),
        migrations.AddField(
            model_name='deck',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='card',
            name='position',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
