# Generated by Django 6.0 on 2026-03-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renda', '0004_remove_tag_uniq_tag_name_per_user_remove_deck_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
